sudo: false
language: node_js
node_js:
  - "stable"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - export CC=`which gcc-4.8`
  - export CXX=`which g++-4.8`

branches:
  only:
    - master
